[tool.poetry]
name = "sql-alchemy"
version = "0.1.0"
description = ""
authors = ["Nik Kor <3357381Nk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
