"""Initial migration

Revision ID: fb05909c09bb
Revises: b648e36f1a4c
Create Date: 2024-08-12 14:13:33.441021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb05909c09bb'
down_revision: Union[str, None] = 'b648e36f1a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('Tutors',
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tutor_id')
    )
    op.create_table('Students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.group_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('Subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['Tutors.tutor_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('Marks',
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['Students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['Subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('mark_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Marks')
    op.drop_table('Subjects')
    op.drop_table('Students')
    op.drop_table('Tutors')
    op.drop_table('Groups')
    # ### end Alembic commands ###
